"""Pure protocol implementation for JFL Active panels.

Author: Jonis Maurin Ceará <jmceara AT gmail.com>
Based on the code developed by Carlos Jose Fernandes,
available at https://github.com/fernac03/JFL_ACTIVE

This package is **pure**: standard library only, no `homeassistant` imports, no I/O and no sockets.
It parses and builds frames and nothing else, so it can be imported, unit-tested and fuzzed on its
own — and so `mypy --strict` can be enforced on it without dragging in Home Assistant's typing.

The shape of a session, for whoever wires this to a socket in Sprint 2::

    reader = FrameReader()
    seq = Seq()

    for frame in reader.feed(data):            # length-driven, self-healing
        packet = decode(frame)                 # dispatches on frame.cmd, never on length
        match packet:
            case ConnectionInfo():
                send(build_connection_ack(packet.seq))     # the PANEL's seq, not ours
            case PanelEvent():
                send(build_event_ack(packet.seq, packet.counter))   # even if decoding failed
            case KeepAlive():
                send(build_keepalive_ack(packet.seq))

    send(build_fence_arm(seq.next()))          # no password, no lockout risk

Three rules this package exists to enforce, each of which the old integration breaks:

* Frames are delimited by the **length byte**, never by the size of a read.
* Panel-initiated frames are answered with the **panel's** sequence byte.
* Commands answer with a full status frame, not an acknowledgement — and that frame is not the
  final state. Re-read the status after any command.

Every verified fact behind this code is cached in `docs/protocol/`. Read those rather than the PDFs.
"""

from __future__ import annotations

from .capabilities import JflCapabilities
from .contact_id import (
    CODES,
    UNKNOWN_CODE,
    ZONE_ALERTS,
    ContactIdCode,
    classify,
    is_fence,
    lookup,
    subject_of,
    zone_alert,
)
from .decode import (
    bcd_to_int,
    bitmap_to_flags,
    decode,
    decode_clock,
    flags_to_bitmap,
    nibbles_to_zones,
)
from .encode import (
    DEFAULT_KEEPALIVE_MINUTES,
    FENCE_PARTITION,
    NO_PASSWORD,
    Password,
    Seq,
    build_arm,
    build_arm_away,
    build_arm_stay,
    build_auth,
    build_auth_arm,
    build_auth_bypass,
    build_auth_fence,
    build_auth_pgm,
    build_bypass_bitmap,
    build_connection_ack,
    build_disarm,
    build_event_ack,
    build_events_read,
    build_fence_arm,
    build_fence_disarm,
    build_keepalive_ack,
    build_login,
    build_monitor_status_request,
    build_pgm_off,
    build_pgm_on,
    build_programming_read,
    build_set_datetime,
    build_status_request,
    build_wireless_read,
)
from .frames import (
    Frame,
    FrameReader,
    JflProtocolError,
    PanelNotConnectedError,
    UnsupportedProtocolError,
    build_frame,
    checksum_for,
    is_valid,
    xor_all,
)
from .models import (
    EVENTS_PER_PAGE,
    MODELS,
    UNKNOWN_MODEL,
    WIRELESS_MODELS,
    WIRELESS_PER_PAGE,
    ArmMode,
    AuthFunc,
    Cmd,
    CommandAck,
    CommandResponse,
    ConnectionInfo,
    EventBuffer,
    EventKind,
    EventRecord,
    EventSubject,
    FencePermissions,
    FenceState,
    KeepAlive,
    LoginInfo,
    LoginResult,
    ModelSpec,
    MonitorStatus,
    Packet,
    PanelEvent,
    PanelStatus,
    PartitionPermissions,
    PartitionState,
    ProblemFlag,
    Problems,
    ProgrammingBlock,
    SignalQuality,
    UnknownPacket,
    WirelessDevice,
    WirelessInventory,
    ZoneAlert,
    ZoneState,
    ZoneStatus,
    spec_for,
)
from .programming import (
    MAX_READ,
    PGM_FUNCTION_LABELS,
    ZONE_TYPE_NAMES,
    GlobalZoneOptions,
    HolidayRecord,
    PartitionRecord,
    PgmFunction,
    PgmRecord,
    ReadRequest,
    TimerSettings,
    UserPermissions,
    UserRecord,
    WirelessRecord,
    ZoneRecord,
    ZoneSensitivity,
    decode_name,
    parse_auto_arm_time,
    parse_global_zone_options,
    parse_holidays,
    parse_partitions,
    parse_pgms,
    parse_timers,
    parse_users,
    parse_wireless,
    parse_zones,
    plan_read,
    plan_region,
    zone_address,
)

__all__ = [
    "CODES",
    "DEFAULT_KEEPALIVE_MINUTES",
    "EVENTS_PER_PAGE",
    "FENCE_PARTITION",
    "MAX_READ",
    "MODELS",
    "NO_PASSWORD",
    "PGM_FUNCTION_LABELS",
    "UNKNOWN_CODE",
    "UNKNOWN_MODEL",
    "WIRELESS_MODELS",
    "WIRELESS_PER_PAGE",
    "ZONE_ALERTS",
    "ZONE_TYPE_NAMES",
    "ArmMode",
    "AuthFunc",
    "Cmd",
    "CommandAck",
    "CommandResponse",
    "ConnectionInfo",
    "ContactIdCode",
    "EventBuffer",
    "EventKind",
    "EventRecord",
    "EventSubject",
    "FencePermissions",
    "FenceState",
    "Frame",
    "FrameReader",
    "GlobalZoneOptions",
    "HolidayRecord",
    "JflCapabilities",
    "JflProtocolError",
    "KeepAlive",
    "LoginInfo",
    "LoginResult",
    "ModelSpec",
    "MonitorStatus",
    "Packet",
    "PanelEvent",
    "PanelNotConnectedError",
    "PanelStatus",
    "PartitionPermissions",
    "PartitionRecord",
    "PartitionState",
    "Password",
    "PgmFunction",
    "PgmRecord",
    "ProblemFlag",
    "Problems",
    "ProgrammingBlock",
    "ReadRequest",
    "Seq",
    "SignalQuality",
    "TimerSettings",
    "UnknownPacket",
    "UnsupportedProtocolError",
    "UserPermissions",
    "UserRecord",
    "WirelessDevice",
    "WirelessInventory",
    "WirelessRecord",
    "ZoneAlert",
    "ZoneRecord",
    "ZoneSensitivity",
    "ZoneState",
    "ZoneStatus",
    "bcd_to_int",
    "bitmap_to_flags",
    "build_arm",
    "build_arm_away",
    "build_arm_stay",
    "build_auth",
    "build_auth_arm",
    "build_auth_bypass",
    "build_auth_fence",
    "build_auth_pgm",
    "build_bypass_bitmap",
    "build_connection_ack",
    "build_disarm",
    "build_event_ack",
    "build_events_read",
    "build_fence_arm",
    "build_fence_disarm",
    "build_frame",
    "build_keepalive_ack",
    "build_login",
    "build_monitor_status_request",
    "build_pgm_off",
    "build_pgm_on",
    "build_programming_read",
    "build_set_datetime",
    "build_status_request",
    "build_wireless_read",
    "checksum_for",
    "classify",
    "decode",
    "decode_clock",
    "decode_name",
    "flags_to_bitmap",
    "is_fence",
    "is_valid",
    "lookup",
    "nibbles_to_zones",
    "parse_auto_arm_time",
    "parse_global_zone_options",
    "parse_holidays",
    "parse_partitions",
    "parse_pgms",
    "parse_timers",
    "parse_users",
    "parse_wireless",
    "parse_zones",
    "plan_read",
    "plan_region",
    "spec_for",
    "subject_of",
    "xor_all",
    "zone_address",
    "zone_alert",
]
